# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03f2edabd06800271bd7e8cd739f5dfc21c218e0f6c38f090f8790508f746a8a77c661520a0d409d534e440fda159a715cd8af3c72e639a50e98fe6938e08646

test:
  secret_key_base: b8344025f469733fdaeafa7a4cc55964a223b4ea09ebf5e58ed3832ec4d46ac8706e77bbaaa0fd07232a94951d1af17734b7e300495573c0747af8e4b20bf140

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
