# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a14801f084df65b14cc9abb53fadcb87d2e2a4a4a242999a89101a52620ad036bc6257a2574430655ade258db8b5079529a56527767adce6a56163d822b694e

test:
  secret_key_base: 6e8b3ad970113e284c283b3dadb5b18011e216205ecddaec78f6f2ca6c2b051ef8fc6a7c7a9d042c671f11a9de24d8ba690ba029e4f9a5391c236bfe21fef3a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
